# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SFCS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'RealmSwift'
pod 'Firebase/Firestore'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'SDWebImageSwiftUI'
pod 'TensorFlowLiteSwift'

 # Pods for momo
pod "MomoiOSSwiftSdk", :git => "https://github.com/momodevelopment/MomoiOSSwiftSdk.git", :branch => "master", submodules: true

  # Pods for SFCS

  target 'SFCSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SFCSUITests' do
    # Pods for testing
  end

end
